/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroudMask: typeof import('./../src/components/common/BackgroudMask.vue')['default']
    ContentRecommend: typeof import('./../src/components/ContentRecommend.vue')['default']
    MainHead: typeof import('./../src/components/MainHead.vue')['default']
    MainLeftMenu: typeof import('./../src/components/MainLeftMenu.vue')['default']
    MainRightContent: typeof import('./../src/components/MainRightContent.vue')['default']
    MainRightPlayBar: typeof import('./../src/components/MainRightPlayBar.vue')['default']
    MusicPlay: typeof import('./../src/components/MusicPlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SysSettings: typeof import('./../src/components/SysSettings.vue')['default']
    SysSkins: typeof import('./../src/components/SysSkins.vue')['default']
    SysUserInfo: typeof import('./../src/components/SysUserInfo.vue')['default']
  }
}
