/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BackgroudMask: typeof import('./../src/components/common/BackgroudMask.vue')['default']
    MainLeftMenu: typeof import('./../src/components/MainLeftMenu.vue')['default']
    MainRightContent: typeof import('./../src/components/MainRightContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZoeyMessage: typeof import('./../src/components/common/ZoeyMessage.vue')['default']
  }
}
